plugins: [jekyll-paginate]

permalink: /:categories/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 10
paginate_path: "page/:num"


defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      styles : [highlight.css,post.css]
      scripts : [post.js]



title: "Coding Master"
email: jinah0818@gmail.com
description: "알고리즘을 더 잘하고 싶은 사람들"
github:
  username: COMA-coding-master
  admin: jinah92 Ysp9714
swiftype:
  searchId: iXZyPokVfxFaBTvi64Y6
comment:
    repo: COMA-coding-master.github.io
    client_id: 12e561de47d1c907f757
    client_secret: 58cba64a7ef64bdc7f11bfe5cf79463dfd9fc3a6

url: "https://coma-coding-master.github.io"
imgrepo: "https://coma-coding-master.github.io/static/img"

#     issues_repo: COMA-coding-master/COMA-coding-master.github.io
#url: "http://127.0.0.1:4000"
#imgrepo: "http://127.0.0.1:4000/static/img"

